title: Employ Me
email: mail@harrisonbarker.co.uk
description: >- # this means to ignore newlines until "baseurl:"

baseurl: "/EmployMe" # the subpath of your site, e.g. /blog
url: "https://mrharrisonbarker.github.io" # the base hostname & protocol for your site, e.g. http://example.com
repository: mrharrisonbarker/employme
twitter: harrisonbbarker
github: mrharrisonbarker
linkedin: harrisonbarker

paginate: 4
paginate_path: "/:num/"

#markdown: kramdown
#
#kramdown:
#  input: GFM
#  syntax_highlighter: rouge

google_analytics:
comments: false
disqus:

author: Harrison Barker
author_pic:
author_bio: >-

# Build settings
theme: null
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
permalink: /:title

theme_switcher: false

# Allows all pages to be put into `_pages` folder
# for easier navigation and better SEO.
collections:
  pages:
    output: true
    permalink: /:title

# Exclude from processing.
exclude:
  - ".jekyll-cache"
  - "Gemfile"
  - "Gemfile.lock"
